# Generated by Django 4.2.4 on 2024-05-04 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 20, 56, 43, 579178)),
        ),
        migrations.CreateModel(
            name='UnderRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_return_date', models.DateTimeField()),
                ('repairing_company', models.CharField(max_length=100)),
                ('under_repair', models.BooleanField(default=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.reports')),
            ],
        ),
    ]
