# Generated by Django 4.2.4 on 2024-05-04 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_reports_created_at_underrepair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 23, 2, 8, 910814)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='stage',
            field=models.IntegerField(default=1),
        ),
    ]
