# Generated by Django 4.2.4 on 2024-05-04 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_reports_created_at_alter_reports_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 23, 24, 51, 837795)),
        ),
    ]
