# Generated by Django 5.0.2 on 2024-02-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('composite_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computing_Resources',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('building_block', models.CharField(max_length=100)),
                ('building_floor', models.IntegerField()),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('specifications', models.TextField()),
                ('oem_name', models.TextField()),
                ('vendor', models.TextField()),
                ('purchase_date', models.DateField()),
                ('warranty_type', models.CharField(choices=[('stock', 'Stock'), ('extended', 'Extended'), ('amc', 'AMC')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('attached_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='composite_devices.compositedevices')),
            ],
        ),
        migrations.CreateModel(
            name='IO_Resources',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('building_block', models.CharField(max_length=100)),
                ('building_floor', models.IntegerField()),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('specifications', models.TextField()),
                ('oem_name', models.TextField()),
                ('vendor', models.TextField()),
                ('purchase_date', models.DateField()),
                ('warranty_type', models.CharField(choices=[('stock', 'Stock'), ('extended', 'Extended'), ('amc', 'AMC')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('attached_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='composite_devices.compositedevices')),
            ],
        ),
        migrations.CreateModel(
            name='NW_Resources',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('building_block', models.CharField(max_length=100)),
                ('building_floor', models.IntegerField()),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('specifications', models.TextField()),
                ('oem_name', models.TextField()),
                ('vendor', models.TextField()),
                ('purchase_date', models.DateField()),
                ('warranty_type', models.CharField(choices=[('stock', 'Stock'), ('extended', 'Extended'), ('amc', 'AMC')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('attached_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='composite_devices.compositedevices')),
            ],
        ),
        migrations.CreateModel(
            name='SW_Resources',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('building_block', models.CharField(max_length=100)),
                ('building_floor', models.IntegerField()),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('specifications', models.TextField()),
                ('oem_name', models.TextField()),
                ('vendor', models.TextField()),
                ('purchase_date', models.DateField()),
                ('warranty_type', models.CharField(choices=[('stock', 'Stock'), ('extended', 'Extended'), ('amc', 'AMC')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('attached_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='composite_devices.compositedevices')),
            ],
        ),
    ]
